<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="10" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="My Test Suite" duration-ms="0" started-at="2015-08-13T17:57:17Z" finished-at="2015-08-13T17:57:17Z">
    <groups>
    </groups>
  </suite> <!-- My Test Suite -->
  <suite name="Parallel test runs" duration-ms="6039065" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T17:57:16Z">
    <groups>
    </groups>
    <test name="T_03" duration-ms="909306" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T16:31:46Z">
      <class name="firstestngpackage.ThirdTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.ThirdTestNGFile@e580929]" name="test" duration-ms="909294" started-at="2015-08-13T09:16:37Z" finished-at="2015-08-13T09:31:46Z">
          <exception class="org.parse4j.ParseException">
            <message>
              <![CDATA[Connection failed with Parse servers.  Log: Connection reset]]>
            </message>
            <full-stacktrace>
              <![CDATA[ParseException [code=100, error=Connection failed with Parse servers.  Log: Connection reset]
	at org.parse4j.command.ParseResponse.getConnectionFailedException(ParseResponse.java:51)
	at org.parse4j.command.ParseCommand.perform(ParseCommand.java:58)
	at org.parse4j.ParseObject.save(ParseObject.java:459)
	at firstestngpackage.ThirdTestNGFile.test(ThirdTestNGFile.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.parse4j.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.ThirdTestNGFile -->
    </test> <!-- T_03 -->
    <test name="T_05" duration-ms="968156" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T16:32:45Z">
      <class name="firstestngpackage.FifthTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.FifthTestNGFile@1e643faf]" name="test" duration-ms="968147" started-at="2015-08-13T09:16:37Z" finished-at="2015-08-13T09:32:45Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[value may not be null.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: value may not be null.
	at org.parse4j.ParseObject.put(ParseObject.java:357)
	at org.parse4j.ParseObject.put(ParseObject.java:339)
	at firstestngpackage.FifthTestNGFile.test(FifthTestNGFile.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.FifthTestNGFile -->
    </test> <!-- T_05 -->
    <test name="T_02" duration-ms="1400479" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T16:39:58Z">
      <class name="firstestngpackage.SecondTestNGFile">
        <test-method status="PASS" signature="test()[pri:0, instance:firstestngpackage.SecondTestNGFile@d041cf]" name="test" duration-ms="1400466" started-at="2015-08-13T09:16:37Z" finished-at="2015-08-13T09:39:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.SecondTestNGFile -->
    </test> <!-- T_02 -->
    <test name="T_08" duration-ms="739913" started-at="2015-08-13T16:39:58Z" finished-at="2015-08-13T16:52:18Z">
      <class name="firstestngpackage.EighthTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.EighthTestNGFile@2812cbfa]" name="test" duration-ms="739912" started-at="2015-08-13T09:39:58Z" finished-at="2015-08-13T09:52:18Z">
          <exception class="org.parse4j.ParseException">
            <message>
              <![CDATA[Connection failed with Parse servers.  Log: Connection reset]]>
            </message>
            <full-stacktrace>
              <![CDATA[ParseException [code=100, error=Connection failed with Parse servers.  Log: Connection reset]
	at org.parse4j.command.ParseResponse.getConnectionFailedException(ParseResponse.java:51)
	at org.parse4j.command.ParseCommand.perform(ParseCommand.java:58)
	at org.parse4j.ParseObject.save(ParseObject.java:459)
	at firstestngpackage.EighthTestNGFile.test(EighthTestNGFile.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.parse4j.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.EighthTestNGFile -->
    </test> <!-- T_08 -->
    <test name="T_01" duration-ms="2669091" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T17:01:06Z">
      <class name="firstestngpackage.FirstTestNGFile">
        <test-method status="PASS" signature="test()[pri:0, instance:firstestngpackage.FirstTestNGFile@721e0f4f]" name="test" duration-ms="2669076" started-at="2015-08-13T09:16:37Z" finished-at="2015-08-13T10:01:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.FirstTestNGFile -->
    </test> <!-- T_01 -->
    <test name="T_04" duration-ms="2727840" started-at="2015-08-13T16:16:37Z" finished-at="2015-08-13T17:02:05Z">
      <class name="firstestngpackage.FourthTestNGFile">
        <test-method status="PASS" signature="test()[pri:0, instance:firstestngpackage.FourthTestNGFile@7c30a502]" name="test" duration-ms="2727831" started-at="2015-08-13T09:16:37Z" finished-at="2015-08-13T10:02:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.FourthTestNGFile -->
    </test> <!-- T_04 -->
    <test name="T_06" duration-ms="2254806" started-at="2015-08-13T16:31:47Z" finished-at="2015-08-13T17:09:21Z">
      <class name="firstestngpackage.SixthTestNGFile">
        <test-method status="PASS" signature="test()[pri:0, instance:firstestngpackage.SixthTestNGFile@36d64342]" name="test" duration-ms="2254805" started-at="2015-08-13T09:31:47Z" finished-at="2015-08-13T10:09:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.SixthTestNGFile -->
    </test> <!-- T_06 -->
    <test name="T_07" duration-ms="5070749" started-at="2015-08-13T16:32:45Z" finished-at="2015-08-13T17:57:16Z">
      <class name="firstestngpackage.SeventhTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.SeventhTestNGFile@17c68925]" name="test" duration-ms="5070747" started-at="2015-08-13T09:32:45Z" finished-at="2015-08-13T10:57:16Z">
          <exception class="org.parse4j.ParseException">
            <message>
              <![CDATA[Connection failed with Parse servers.  Log: Permission denied]]>
            </message>
            <full-stacktrace>
              <![CDATA[ParseException [code=100, error=Connection failed with Parse servers.  Log: Permission denied]
	at org.parse4j.command.ParseResponse.getConnectionFailedException(ParseResponse.java:51)
	at org.parse4j.command.ParseCommand.perform(ParseCommand.java:58)
	at org.parse4j.ParseObject.save(ParseObject.java:459)
	at firstestngpackage.SeventhTestNGFile.test(SeventhTestNGFile.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.parse4j.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.SeventhTestNGFile -->
    </test> <!-- T_07 -->
    <test name="T_10" duration-ms="3369922" started-at="2015-08-13T17:01:06Z" finished-at="2015-08-13T17:57:16Z">
      <class name="firstestngpackage.TenthTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.TenthTestNGFile@6bf256fa]" name="test" duration-ms="3369921" started-at="2015-08-13T10:01:06Z" finished-at="2015-08-13T10:57:16Z">
          <exception class="org.parse4j.ParseException">
            <message>
              <![CDATA[Connection failed with Parse servers.  Log: Permission denied]]>
            </message>
            <full-stacktrace>
              <![CDATA[ParseException [code=100, error=Connection failed with Parse servers.  Log: Permission denied]
	at org.parse4j.command.ParseResponse.getConnectionFailedException(ParseResponse.java:51)
	at org.parse4j.command.ParseCommand.perform(ParseCommand.java:58)
	at org.parse4j.ParseObject.save(ParseObject.java:459)
	at firstestngpackage.TenthTestNGFile.test(TenthTestNGFile.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.parse4j.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.TenthTestNGFile -->
    </test> <!-- T_10 -->
    <test name="T_09" duration-ms="3898550" started-at="2015-08-13T16:52:18Z" finished-at="2015-08-13T17:57:16Z">
      <class name="firstestngpackage.NinthTestNGFile">
        <test-method status="FAIL" signature="test()[pri:0, instance:firstestngpackage.NinthTestNGFile@60f82f98]" name="test" duration-ms="3898549" started-at="2015-08-13T09:52:18Z" finished-at="2015-08-13T10:57:16Z">
          <exception class="org.parse4j.ParseException">
            <message>
              <![CDATA[Connection failed with Parse servers.  Log: Permission denied]]>
            </message>
            <full-stacktrace>
              <![CDATA[ParseException [code=100, error=Connection failed with Parse servers.  Log: Permission denied]
	at org.parse4j.command.ParseResponse.getConnectionFailedException(ParseResponse.java:51)
	at org.parse4j.command.ParseCommand.perform(ParseCommand.java:58)
	at org.parse4j.ParseObject.save(ParseObject.java:459)
	at firstestngpackage.NinthTestNGFile.test(NinthTestNGFile.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.parse4j.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- firstestngpackage.NinthTestNGFile -->
    </test> <!-- T_09 -->
  </suite> <!-- Parallel test runs -->
</testng-results>
